### ISSUE TITLE
[PE-D][Tester B] UG documentation flaw

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W13-1/tp#108] opened 2023-03-31 19:15 UTC
![image.png](https://raw.githubusercontent.com/YuanXun9834/ped/main/files/738cbd7a-5cef-4316-abaf-ba6dc7a06b0b.png)
Command summary for prescribe is wrong.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: YuanXun9834/ped#11

**Comment by PeanutButters93** [comment] 2023-04-03 12:42
Duplicate of #116

**Closed** 2023-04-03 12:59 UTC
Labels: duplicate
